repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.12
    hooks:
      - id: markdown-link-check
      - id: terraform-fmt
      - id: terraform-validate
      - id: tflint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: no-commit-to-branch
      - id: trailing-whitespace
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: v0.14.1
    hooks:
      - id: terraform-docs-go
