name: markdown-lint

on: [push,pull_request]

jobs:
  markdown-lint:
    name: "Markdown lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: avto-dev/markdown-lint@v1
        with:
          args: 'docs'
